from typing import TypedDict


class GraphState(TypedDict):
    # ── Ticket / Issue ──────────────────────────────────────────────────────
    ticket_text: str        # Issue body used as the coding brief
    issue_number: int       # GitHub issue number (0 if manual run)
    branch_name: str        # Git branch created for the fix
    repo_url: str           # HTTPS clone URL of the target repo

    # ── Spec loop ───────────────────────────────────────────────────────────
    spec: str               # Technical specification generated by Spec Agent
    spec_feedback: str      # Validator feedback ("VALID" or critique)
    spec_iteration_count: int  # Number of spec review cycles

    # ── Coding / Test loop ─────────────────────────────────────────────────
    test_output: str        # Raw pytest stdout/stderr from Docker sandbox
    tests_passed: bool      # Whether the last test run passed
    iteration_count: int    # Number of coding iterations attempted

    # ── PR ──────────────────────────────────────────────────────────────────
    pr_url: str             # URL of the opened GitHub Pull Request
