from typing import TypedDict


class GraphState(TypedDict):
    # ── Logging ─────────────────────────────────────────────────────────────
    log_file_path: str      # Absolute path to the request log file
    chat_log_file_path: str # Absolute path to the chat log file
    total_tokens: int       # Cumulative token count for this request

    # ── Ticket / Issue ──────────────────────────────────────────────────────
    ticket_text: str        # Issue body used as the coding brief
    issue_number: int       # GitHub issue number (0 if manual run)
    branch_name: str        # Git branch created for the fix
    repo_url: str           # HTTPS clone URL of the target repo

    # ── Language detection (language-agnostic pipeline) ─────────────────────
    detected_language: str  # Primary language detected in workspace (e.g. "Java", "Python")
    detected_framework: str # Framework detected in workspace   (e.g. "Spring Boot", "Django")

    # ── Spec loop ───────────────────────────────────────────────────────────
    spec: str               # Technical specification generated by Spec Agent
    spec_feedback: str      # Validator feedback ("VALID" or critique)
    spec_iteration_count: int  # Number of spec review cycles

    # ── Coding / Test loop ─────────────────────────────────────────────────
    test_output: str        # Raw test runner stdout/stderr from Docker sandbox
    tests_passed: bool      # Whether the last test run passed
    tests_generated: bool   # Whether the Testing Agent has generated tests
    iteration_count: int    # Number of coding iterations attempted

    # ── PR ──────────────────────────────────────────────────────────────────
    pr_url: str             # URL of the opened GitHub Pull Request
